"""empty message

Revision ID: 4b370d90aab7
Revises: c8ccedf36464
Create Date: 2024-11-23 05:54:13.848128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b370d90aab7'
down_revision = 'c8ccedf36464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('positions', sa.String(length=255), nullable=True),
    sa.Column('teams', sa.String(length=255), nullable=True),
    sa.Column('awards', sa.String(length=255), nullable=True),
    sa.Column('case_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('team', sa.String(length=5), nullable=True),
    sa.Column('pos', sa.String(length=5), nullable=True),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('rebounds', sa.Float(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=False),
    sa.Column('steals', sa.Float(), nullable=True),
    sa.Column('blocks', sa.Float(), nullable=True),
    sa.Column('fg_percentage', sa.Float(), nullable=True),
    sa.Column('three_point_percentage', sa.Float(), nullable=True),
    sa.Column('ft_percentage', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.create_index('ix_post_season_player_season', ['player_id', 'season'], unique=False)

    op.create_table('regular_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('team', sa.String(length=5), nullable=True),
    sa.Column('pos', sa.String(length=5), nullable=True),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('rebounds', sa.Float(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=False),
    sa.Column('steals', sa.Float(), nullable=True),
    sa.Column('blocks', sa.Float(), nullable=True),
    sa.Column('fg_percentage', sa.Float(), nullable=True),
    sa.Column('three_point_percentage', sa.Float(), nullable=True),
    sa.Column('ft_percentage', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.create_index('ix_regular_season_player_season', ['player_id', 'season'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.drop_index('ix_regular_season_player_season')

    op.drop_table('regular_season')
    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.drop_index('ix_post_season_player_season')

    op.drop_table('post_season')
    op.drop_table('player_info')
    op.drop_table('player')
    # ### end Alembic commands ###
