"""empty message

Revision ID: 6bf4aa57c865
Revises: 861d0b5cfacb
Create Date: 2024-11-23 06:22:13.642815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bf4aa57c865'
down_revision = '861d0b5cfacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
