"""empty message

Revision ID: 861d0b5cfacb
Revises: 4b370d90aab7
Create Date: 2024-11-23 06:18:08.706031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '861d0b5cfacb'
down_revision = '4b370d90aab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_info', schema=None) as batch_op:
        batch_op.alter_column('awards',
               existing_type=mysql.VARCHAR(length=5000),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('player_info', schema=None) as batch_op:
        batch_op.alter_column('awards',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###
