"""Added new stats columns

Revision ID: c8ccedf36464
Revises: 
Create Date: 2024-11-11 14:02:00.745078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ccedf36464'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fg_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('three_point_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ft_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('turnovers', sa.Float(), nullable=True))

    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fg_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('three_point_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ft_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('turnovers', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regular_season', schema=None) as batch_op:
        batch_op.drop_column('turnovers')
        batch_op.drop_column('ft_percentage')
        batch_op.drop_column('three_point_percentage')
        batch_op.drop_column('fg_percentage')

    with op.batch_alter_table('post_season', schema=None) as batch_op:
        batch_op.drop_column('turnovers')
        batch_op.drop_column('ft_percentage')
        batch_op.drop_column('three_point_percentage')
        batch_op.drop_column('fg_percentage')

    # ### end Alembic commands ###
